### PR TITLE
Symfony 6 support

### PR DESCRIPTION
**Pull request by Kleinkind**
- allowed symfony 6 in version constraints
- added ci-config for php 8.1

### CODE REVIEW

**Comment by dbu** [comment]
thanks a lot!

i fixed the lowest version build in master. can you please rebase on master (and fix the conflict)? then we should see a green build. i will tag a release when this is merged.

**Comment by Kleinkind** [comment]
Oh nice, thank you @dbu 
The new build is on its way 👍

**Comment by dbu** [comment]
thanks! i will tag a release shortly

**Comment by dbu** [comment]
https://github.com/jackalope/jackalope-fs/releases/tag/0.0.4

**Pull request merged**
